/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IdRouteImport } from './routes/$id'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiProducersRouteImport } from './routes/api/producers'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiViewIdRouteImport } from './routes/api/view.$id'
import { Route as ApiVideosIdRouteImport } from './routes/api/videos.$id'
import { Route as ApiPosterIdRouteImport } from './routes/api/poster.$id'
import { Route as ApiMediaIdRouteImport } from './routes/api/media.$id'
import { Route as ApiCaptionsIdRouteImport } from './routes/api/captions.$id'
import { Route as ApiVideosIdSidecarsRouteImport } from './routes/api/videos.$id.sidecars'

const IdRoute = IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProducersRoute = ApiProducersRouteImport.update({
  id: '/api/producers',
  path: '/api/producers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiViewIdRoute = ApiViewIdRouteImport.update({
  id: '/api/view/$id',
  path: '/api/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideosIdRoute = ApiVideosIdRouteImport.update({
  id: '/api/videos/$id',
  path: '/api/videos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPosterIdRoute = ApiPosterIdRouteImport.update({
  id: '/api/poster/$id',
  path: '/api/poster/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/api/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaptionsIdRoute = ApiCaptionsIdRouteImport.update({
  id: '/api/captions/$id',
  path: '/api/captions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideosIdSidecarsRoute = ApiVideosIdSidecarsRouteImport.update({
  id: '/sidecars',
  path: '/sidecars',
  getParentRoute: () => ApiVideosIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/api/ping': typeof ApiPingRoute
  '/api/producers': typeof ApiProducersRoute
  '/api/version': typeof ApiVersionRoute
  '/api/captions/$id': typeof ApiCaptionsIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/poster/$id': typeof ApiPosterIdRoute
  '/api/videos/$id': typeof ApiVideosIdRouteWithChildren
  '/api/view/$id': typeof ApiViewIdRoute
  '/api/videos/$id/sidecars': typeof ApiVideosIdSidecarsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/api/ping': typeof ApiPingRoute
  '/api/producers': typeof ApiProducersRoute
  '/api/version': typeof ApiVersionRoute
  '/api/captions/$id': typeof ApiCaptionsIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/poster/$id': typeof ApiPosterIdRoute
  '/api/videos/$id': typeof ApiVideosIdRouteWithChildren
  '/api/view/$id': typeof ApiViewIdRoute
  '/api/videos/$id/sidecars': typeof ApiVideosIdSidecarsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$id': typeof IdRoute
  '/api/ping': typeof ApiPingRoute
  '/api/producers': typeof ApiProducersRoute
  '/api/version': typeof ApiVersionRoute
  '/api/captions/$id': typeof ApiCaptionsIdRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/poster/$id': typeof ApiPosterIdRoute
  '/api/videos/$id': typeof ApiVideosIdRouteWithChildren
  '/api/view/$id': typeof ApiViewIdRoute
  '/api/videos/$id/sidecars': typeof ApiVideosIdSidecarsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$id'
    | '/api/ping'
    | '/api/producers'
    | '/api/version'
    | '/api/captions/$id'
    | '/api/media/$id'
    | '/api/poster/$id'
    | '/api/videos/$id'
    | '/api/view/$id'
    | '/api/videos/$id/sidecars'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$id'
    | '/api/ping'
    | '/api/producers'
    | '/api/version'
    | '/api/captions/$id'
    | '/api/media/$id'
    | '/api/poster/$id'
    | '/api/videos/$id'
    | '/api/view/$id'
    | '/api/videos/$id/sidecars'
  id:
    | '__root__'
    | '/'
    | '/$id'
    | '/api/ping'
    | '/api/producers'
    | '/api/version'
    | '/api/captions/$id'
    | '/api/media/$id'
    | '/api/poster/$id'
    | '/api/videos/$id'
    | '/api/view/$id'
    | '/api/videos/$id/sidecars'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdRoute: typeof IdRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiProducersRoute: typeof ApiProducersRoute
  ApiVersionRoute: typeof ApiVersionRoute
  ApiCaptionsIdRoute: typeof ApiCaptionsIdRoute
  ApiMediaIdRoute: typeof ApiMediaIdRoute
  ApiPosterIdRoute: typeof ApiPosterIdRoute
  ApiVideosIdRoute: typeof ApiVideosIdRouteWithChildren
  ApiViewIdRoute: typeof ApiViewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/producers': {
      id: '/api/producers'
      path: '/api/producers'
      fullPath: '/api/producers'
      preLoaderRoute: typeof ApiProducersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/view/$id': {
      id: '/api/view/$id'
      path: '/api/view/$id'
      fullPath: '/api/view/$id'
      preLoaderRoute: typeof ApiViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/videos/$id': {
      id: '/api/videos/$id'
      path: '/api/videos/$id'
      fullPath: '/api/videos/$id'
      preLoaderRoute: typeof ApiVideosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/poster/$id': {
      id: '/api/poster/$id'
      path: '/api/poster/$id'
      fullPath: '/api/poster/$id'
      preLoaderRoute: typeof ApiPosterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/captions/$id': {
      id: '/api/captions/$id'
      path: '/api/captions/$id'
      fullPath: '/api/captions/$id'
      preLoaderRoute: typeof ApiCaptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/videos/$id/sidecars': {
      id: '/api/videos/$id/sidecars'
      path: '/sidecars'
      fullPath: '/api/videos/$id/sidecars'
      preLoaderRoute: typeof ApiVideosIdSidecarsRouteImport
      parentRoute: typeof ApiVideosIdRoute
    }
  }
}

interface ApiVideosIdRouteChildren {
  ApiVideosIdSidecarsRoute: typeof ApiVideosIdSidecarsRoute
}

const ApiVideosIdRouteChildren: ApiVideosIdRouteChildren = {
  ApiVideosIdSidecarsRoute: ApiVideosIdSidecarsRoute,
}

const ApiVideosIdRouteWithChildren = ApiVideosIdRoute._addFileChildren(
  ApiVideosIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdRoute: IdRoute,
  ApiPingRoute: ApiPingRoute,
  ApiProducersRoute: ApiProducersRoute,
  ApiVersionRoute: ApiVersionRoute,
  ApiCaptionsIdRoute: ApiCaptionsIdRoute,
  ApiMediaIdRoute: ApiMediaIdRoute,
  ApiPosterIdRoute: ApiPosterIdRoute,
  ApiVideosIdRoute: ApiVideosIdRouteWithChildren,
  ApiViewIdRoute: ApiViewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
